# Generated by Django 5.2.7 on 2025-12-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.URLField(blank=True, help_text='URL da foto de perfil (ex: Gravatar, Imgur)', max_length=500, null=True),
        ),
    ]