# Generated by Django 5.0 on 2025-12-15 19:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id_tag', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cor', models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('danger', 'Vermelho'), ('warning', 'Amarelo'), ('info', 'Ciano'), ('purple', 'Roxo'), ('pink', 'Rosa'), ('orange', 'Laranja')], default='primary', max_length=20)),
                ('icone', models.CharField(default='bi-tag', help_text='Ícone do Bootstrap Icons (ex: bi-star, bi-heart)', max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tag',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='link_whatsapp',
            field=models.URLField(blank=True, help_text='Link do grupo no WhatsApp (ex: https://chat.whatsapp.com/...)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='user.tag'),
        ),
        migrations.CreateModel(
            name='UsuarioTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribuido_em', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='user.tag')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='user.usuario')),
            ],
            options={
                'verbose_name': 'Usuário-Tag',
                'verbose_name_plural': 'Usuários-Tags',
                'db_table': 'usuario_tag',
                'unique_together': {('usuario', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='usuarios', through='user.UsuarioTag', to='user.tag'),
        ),
    ]
