# Generated by Django 5.0 on 2025-12-15 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_solicitacaoaluguel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pagamento', models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão de Crédito'), ('boleto', 'Boleto Bancário'), ('dinheiro', 'Dinheiro')], default='pix', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando Pagamento'), ('processando', 'Processando'), ('aprovado', 'Pago'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_vencimento', models.DateTimeField()),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('chave_pix', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code_pix', models.TextField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=255, null=True)),
                ('linha_digitavel', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluguel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='aluguel.aluguel')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'pagamento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
