# Generated by Django 5.2.7 on 2025-12-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0002_carro_foto_url_carro_preco_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada do carro (motor, câmbio, etc)', null=True),
        ),
    ]