# Generated by Django 5.2.7 on 2025-12-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0003_carro_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='preco_diaria',
            field=models.DecimalField(decimal_places=2, default=150.0, help_text='Preço do aluguel por dia', max_digits=10),
        ),
    ]
