# Generated by Django 5.2.7 on 2025-12-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='foto_url',
            field=models.URLField(blank=True, help_text='URL da foto do carro (ex: Unsplash, Pexels)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='preco_diaria',
            field=models.DecimalField(decimal_places=2, default=150.0, help_text='Preço médio do aluguel por dia', max_digits=10),
        ),
    ]
