# Generated by Django 5.2.7 on 2025-12-12 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carro', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id_aluguel', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('carro', models.ForeignKey(db_column='carro_id_carro', on_delete=django.db.models.deletion.CASCADE, related_name='alugueis', to='carro.carro')),
                ('funcionario', models.ForeignKey(db_column='id_funcionario', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='alugueis_gerenciados', to='user.usuario')),
                ('perfil_cliente', models.ForeignKey(db_column='perfil_cliente_id_perfil_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='alugueis', to='user.perfilcliente')),
            ],
            options={
                'verbose_name': 'Aluguel',
                'verbose_name_plural': 'Aluguéis',
                'db_table': 'aluguel',
                'ordering': ['-criado_em'],
            },
        ),
    ]
