# Generated by Django 5.2.7 on 2025-12-15 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
        ('carro', '0002_carro_foto_url_carro_preco_diaria'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAluguel',
            fields=[
                ('id_solicitacao', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado pelo Cliente')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações do cliente', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluguel_criado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_origem', to='aluguel.aluguel')),
                ('carro', models.ForeignKey(db_column='carro_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='carro.carro')),
                ('perfil_cliente', models.ForeignKey(db_column='perfil_cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='user.perfilcliente')),
            ],
            options={
                'verbose_name': 'Solicitação de Aluguel',
                'verbose_name_plural': 'Solicitações de Aluguel',
                'db_table': 'solicitacao_aluguel',
                'ordering': ['-criado_em'],
            },
        ),
    ]
